---
- name: Perform optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install acmetool
  ansible.builtin.include_tasks: install.yml

- name: configure systemd
  ansible.builtin.include_tasks: systemd.yml

- name: configure acmetool
  ansible.builtin.include_tasks: configure.yml

- name: Copy hook to enable acmetool to restart services
  ansible.builtin.include_tasks: hook.yml

- name: Reload systemd and enable acmetool timer unit
  ansible.builtin.include_tasks: timer.yml
